## Find methods which act upon ?searchClass. ##

# Find method which either accept an argument of type ?searchClass
# or return an object of type ?searchClass

select ?element ?function where {
  bind(javap:java.lang.ClassLoader as ?searchClass)
  {
    ?methodArg javap:hasType ?searchClass.
    ?method javap:argument ?methodArg.
    bind("has argument" as ?function)
  }
  union
  {
    ?method javap:returns ?searchClass.
    bind("returns" as ?function)
  }
  ?method a javap:Method.
  ?method javap:name ?name.
  ?class javap:hasMember ?method.
  ?class javap:name ?className.
  bind(concat(stardog:functions:localname(?class), ".", ?name, "()") as ?element)
}

# This returns a result like:
# +----------------------------------------------------------------------------------+----------------+
# |                                     element                                      |    function    |
# +----------------------------------------------------------------------------------+----------------+
# | "java.io.ObjectInputStream.latestUserDefinedLoader()"                            | "returns"      |
# | "java.lang.Class.checkPackageAccess()"                                           | "has argument" |
# | "java.lang.Class.getClassLoader()"                                               | "returns"      |
# | "java.lang.Class.getClassLoader0()"                                              | "returns"      |
# | "java.lang.Class.forName0()"                                                     | "has argument" |
# | "java.lang.Class.<init>()"                                                       | "has argument" |
# | "java.lang.Class.forName()"                                                      | "has argument" |
# | "javax.swing.UIDefaults.getUIClass()"                                            | "has argument" |
